language: node_js

node_js:
  - "node"
  - "lts/*"
  - "8"
  # - "6" // it should not support the feature of async/await.

services:
  - mongodb

install:
  - "npm install"

script:
  - "npm test"

after_success:
  - npm install coveralls@~3.0.0 --global
  - npm run report-coverage

deploy:
  provider: npm
  email: "arylo.open@gmail.com"
  api_key: "${NPM_TOKEN}"
  on:
    branch: master
